### ISSUE TITLE
Dependency:  RISC-V FFH

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/riscv-brs#10]

**Comment by jones-drew** [comment]
The first draft (v0.1) has been merged to the main branch of its repository[1]. I believe it's ready to begin the ratification process.

[1] https://github.com/riscv-non-isa/riscv-acpi-ffh/blob/main/riscv-ffh.adoc

**Comment by andreiw** [comment]
Going to close this off. The FFH work continues but is not directly referenced from this spec aside from non-normative guidance.
