### ISSUE TITLE
Typo in UEFI_040

### ISSUE THREAD

**Issue by sun409** [riscv-non-isa/riscv-brs#115]
An _**implemenation**_ MAY comply with the UEFI Platform Initialization Specification
An _**implementation**_ MAY comply with the UEFI Platform Initialization Specification

**Comment by andreiw** [comment]
Fixed in https://github.com/riscv-non-isa/riscv-brs/pull/134/commits/a2d6a8ae43fa3cb95902023edc013b14e4341e31
