### ISSUE TITLE
[URT_030] reset note clarification

### ISSUE THREAD

**Issue by dpursell** [riscv-non-isa/riscv-brs#116]
The note under URT_030 currently says:

> The OS MUST call the ResetSystem() runtime service call to reset the system, preferring this to SBI SRST or other platform-specific mechanisms.

Some clarification may be helpful around:

1. whether this applies to a full shutdown as well as reset
I assume it does based on the need to perform tasks on the way out in both cases and `ResetSystem()` providing both, but calling it out explicitly may be helpful.

2. whether the OS is allowed to use ACPI reset/shutdown mechanisms
I assume not in this case, that the OS is only allowed to use UEFI `ResetSystem()`, but the "platform-specific" qualifier is confusing here since IMO things like SBI and ACPI are *not* platform-specific as they are intended to provide generic platform-agnostic interfaces. Removing "platform-specific" may help clarity here (related: issue #35). Additionally, since BRS-I mandates ACPI which may include its own reset/shutdown functionality, it may help to specifically call it out as prohibited along with SBI.

**Comment by andreiw** [comment]
Good notes. Working on it.
