### ISSUE TITLE
Obsolete reference to SEE

### ISSUE THREAD

**Issue by darius-bluespec** [riscv-non-isa/riscv-brs#119]
Chapter 3 states:

> The SEE mandates ...

However, the SEE doesn't exist anymore.

**Comment by andreiw** [comment]
The SBI spec appears to refer to the SEE, fwiw https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/intro.adoc.

That said, I don't think we're going to lose anything by dropping the sentence, because the SBI doc doesn't appear to mandate anything on the hardware.
