### ISSUE TITLE
Dependency: ACPI 6.6: APEI

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/riscv-brs#12]
Does anything RISC-V specific need to be added to e.g. GHESv2 or elsewhere.

**Comment by vlsunil** [comment]
Yes, both ACPI and UEFI spec needs some updates for RISC-V.

**Comment by hschauhan** [comment]
Yes, there is a need to define an ID in SectionType of Section Descriptor. This wold be to differentiate between Error from different type of sources. There is Generic/IA32/IA64/ARM processors defined. We will need one for RISCV. Also, Ventana is working on an high priority software events specification. This would need identification number to differentiate between SDEI of ARM and SSE of RISCV. We at Ventana are working on a proposal for SSE specfication and RAS software architecture.

**Comment by andreiw** [comment]
Need to clearly understand what parts of APEI can be implemented without depending on the ongoing RAS work (i.e. apply to existing hardware). Can fw-first error handling be made a requirement for BRS or not or if it is conditional on certain HW features being implemented.

**Comment by andreiw** [comment]
RAS is not currently in scope.
