### ISSUE TITLE
Redundant language

### ISSUE THREAD

**Issue by darius-bluespec** [riscv-non-isa/riscv-brs#122]
Chapter 5 states:

> This section defines the BRS-I mandatory and optional UEFI
> requirements on top of [9], and is optional and recommended for
> BRS-B. Additional non-normative guidance may be found in the
> Firmware Implementation Guidance section.

This is redundant with Chapter 2.

Similar language is in Chapter 6 and 7.

**Comment by andreiw** [comment]
Well, apparently it wasn't redundant enough as per #128. 

Chapter 2 is a mess.
