### ISSUE TITLE
Inconsistent usage of the meaning of "word"

### ISSUE THREAD

**Issue by darius-bluespec** [riscv-non-isa/riscv-brs#124]
Section 7.1. Type 44 Processor-Specific Data uses WORD to refer to a
specific size of data which is inconsistent with the prevailing RISC-V
usage.

**Comment by andreiw** [comment]
This part of the document I think necessarily has to follow SMBIOS guidelines as far as vocab goes. We can document that.

**Comment by andreiw** [comment]
This should be resolved and further improved on via https://github.com/riscv-non-isa/riscv-brs/pull/131

**Comment by darius-bluespec** [comment]
If QWORD is supposed to be an abbreviation for quadword, now there are
two terms that are inconsistent with prevailing RISC-V usage and
definitions in the RISC-V Instruction Set Manual.
