### ISSUE TITLE
BRS-I EFI Cfg Table Requirement for EFI_DTB_TABLE_GUID

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/riscv-brs#173]
A BRS-I compliant system is allowed to have a DTB present so long as it doesn't include any actual hardware description (as that is provided by ACPI). Such a "dummy" DTB could be installed by OS firmware to provide necessary hand-off info from bootloader to OS, for example, to provide initrd location info (e.g. via /chosen/linux,initrd-start and linux,initrd-end).

**Comment by vlsunil** [comment]
This will need agreement from OS kernel maintainers. IIRC, linux maintainers were against FW passing both ACPI and DTB. The dummy DTB is typically created by the OS itself (linux does it today) but not firmware.

**Comment by vlsunil** [comment]
Sorry I was wrong. Linux supports this today. So, it is allowed.
