### ISSUE TITLE
Why SMBIOS_060?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-brs#186]
For SMBIOS_060, if the RISC-V BRS specification isn't going to recommend any specific strings be in this structure, then why is the existence of this structure recommended?  Would SMBIOS_060 be satisfied with an OEM Strings structure that has the Count field set to zero, for no strings?  If so, then what's the point?  If not, then what does the BRS specification intend the OEM Strings structure to contain?

**Comment by andreiw** [comment]
https://github.com/riscv-non-isa/riscv-brs/pull/194
