### ISSUE TITLE
Clarify SMBIOS_080 for the case when there is no grouping

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-brs#187]
For SMBIOS_080, should a Group Associations structure be implemented even when there are no groupings of anything?  (For example, if there is only one of everything:  processor, hart, cache, etc.?)

**Comment by andreiw** [comment]
This is why it's should and not must. Do it unless there's a good reason not to. We could certainly conditionalize this.

**Comment by andreiw** [comment]
I'm actually tempted to just remove this requirement.

**Comment by andreiw** [comment]
https://github.com/riscv-non-isa/riscv-brs/pull/195
