### ISSUE TITLE
Give a reason for UIO_010

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-brs#200]
The Architecture Review Committee would like the BRS document to include some non-normative justification for UIO_010, which obligates the UEFI firmware to initialize all PCIe root complexes.

**Comment by ved-rivos** [comment]
The non-normative justification slightly hints at the fact that this is a stronger requirement than PCI BIOS envisioned. It will be useful to augment that justification to state why PCIe resource allocation and host bridge configurations are not really standardized across platforms and without the firmware initializing the root complexes it may lead to unexpected behaviors.

**Comment by avpatel** [comment]
The commit https://github.com/riscv-non-isa/riscv-brs/commit/f967ab2d46bf07865d235f058353e384ba28d9ec addresses this issue hence closing it.
