### ISSUE TITLE
Do not recommend deprecated legacy console

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-brs#203]
Section 8.3.9, "SPCR", says:
> When SPCR describes SBI console, the OS must use the SBI Probe extension (FID #3) to detect the appropriate facilities, e.g. the Debug Console Extension (DBCN) or the deprecated legacy console EIDs.

The Architecture Review Committee does not believe the RISC-V BRS document should recommend using the deprecated legacy console.  Instead, there should be a mandatory requirement earlier in the document stating that the DBCN SBI extension must be used when the SBI console is employed.

**Comment by vlsunil** [comment]
I agree. We should  just mandate SBI DBCN when SPCR says SBI console.  @andreiw  @avpatel - any concerns?
