### ISSUE TITLE
Example rules table should say "rules", not "requirements"

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-brs#209]
In the example table at the end of section 1.3, "Testing and Conformance", all uses of the words *requirement* and *requirements* should really be *rule* and *rules*.

**Comment by vlsunil** [comment]
I have raised the PR to update it. https://github.com/riscv-non-isa/riscv-brs/pull/211/commits/6abcd48d0c11f47891ef6aa12a475213bf8c1ff8
Thanks!
