### ISSUE TITLE
Dependency: ACPI: Define _CCA behavior for RISC-V

### ISSUE THREAD

**Issue by andreiw** [riscv-non-isa/riscv-brs#22]
Recommend this as ASWG change to mandate _CCA on any RISC-V platform or force a specific meaning when _CCA is not present.

**Comment by andreiw** [comment]
Should we document _CCA to follow X64/AARCH64 semantics? Defaulting to cache coherence when absent?

**Comment by adurbin-rivos** [comment]
Probably good for a default in ACPI-land. A particular RISC-V Platform may have stronger expectations for all devices in a system to be cache coherent.

**Comment by paul-walmsley-sifive** [comment]
> Recommend this as ASWG change to mandate _CCA on any RISC-V platform or force a specific meaning when _CCA is not present.

Agreed with either of these two approaches

**Comment by andreiw** [comment]
Filed https://mantis.uefi.org/mantis/view.php?id=2407. On RISCV, if the \_CCA object is not supplied, the OSPM will assume the devices are hardware cache coherent.
