### ISSUE TITLE
Bibliography Not Building

### ISSUE THREAD

**Issue by adurbin-rivos** [riscv-non-isa/riscv-brs#30]
I am not getting an error, but the bibliography is not showing up in the pdf. It could very well be my setup. @andreiw is it working for you?

**Comment by adurbin-rivos** [comment]
Tracked it down to this change: e06146edac86dde3f05b556822cd9cf1af842958

**Comment by adurbin-rivos** [comment]
@andreiw fyi

**Comment by andreiw** [comment]
Aaron fixed this a while ago. I just checked and it still works.
