### ISSUE TITLE
Definition of the term "platform", used in the document, is lacking

### ISSUE THREAD

**Issue by darius-bluespec** [riscv-non-isa/riscv-brs#35]

**Comment by adurbin-rivos** [comment]
Lacking in quantity or quality? This could be tied to use issue #34 where if system is the preferred term then it would replace 'platform'.

**Comment by darius-bluespec** [comment]
> Lacking in quantity or quality?

Existence.

> This could be tied to use issue #34 where if system is the preferred term then it would replace 'platform'.

Sure.  Either use it and define it, or don't use it.

**Comment by andreiw** [comment]
Remove usage of "platform"
