### ISSUE TITLE
The relationship between recipes and sections is not clear

### ISSUE THREAD

**Issue by darius-bluespec** [riscv-non-isa/riscv-brs#36]
Recipes should be composed of **sections** in the BRS, not external
specifications.  The current section organization is confusing with
respect to what is and is not a requirement for a particular recipe.
For example, the ACPI section refers to many requirements as
mandatory, but the intention is that entire section is ignored (i.e.,
not mandatory) if not called for in a recipe, such as BRS-B, where
ACPI is intended to be optional.

**Comment by adurbin-rivos** [comment]
Organizationally, do you think we should split into 'common', brs-i, and brs-b? Or orient around brs-i and brs-b w/ those other aspects underneath them? The latter may lead to some duplication, but we could figure out something there.

**Comment by andreiw** [comment]
I think we ended up doing exactly what this ticket proposes.

**Comment by darius-bluespec** [comment]
No you did not.
