### ISSUE TITLE
doc generate fail with: asciidoctor: FAILED: 'asciidoctor-mathematical' could not be loaded

### ISSUE THREAD

**Issue by WangYin3** [riscv-non-isa/riscv-brs#42]
:~/c/n/riscv-os-a-see$ git submodule init
 :~/c/n/riscv-os-a-see$ git log -1
commit f2ea22279d769b854a3fcebbf6c6eabcec4d35fa (HEAD -> main, origin/main, origin/HEAD)
Merge: 54a1a1c 3273c7b
Author: Andrei Warkentin <andrei.warkentin@intel.com>
Date:   Tue May 23 22:50:38 2023 -0500

    Merge pull request #40 from riscv-non-isa/spec-seeding

    spec seeding
 :~/c/n/riscv-os-a-see$ make
asciidoctor-pdf \
-a toc \
-a compress \
-a pdf-style=docs-resources/themes/riscv-pdf.yml \
-a pdf-fontsdir=docs-resources/fonts \
--failure-level=ERROR \
-o profiles.pdf profiles.adoc
Building asciidoc
asciidoctor-pdf \
    --attribute=mathematical-format=svg \
    --attribute=pdf-fontsdir=docs-resources/fonts \
    --attribute=pdf-style=docs-resources/themes/riscv-pdf.yml \
    --failure-level=ERROR \
    --require=asciidoctor-bibtex \
    --require=asciidoctor-diagram \
    --require=asciidoctor-mathematical \
    --out-file=riscv-brs-spec.pdf \
    header.adoc
asciidoctor: FAILED: 'asciidoctor-mathematical' could not be loaded
  Use --trace for backtrace
make: *** [Makefile:9: build] Error 1
asciidoctor: FAILED: input file profiles.adoc is missing

**Comment by andreiw** [comment]
gem install mathematical:1.6.14
gem install asciidoctor-mathematical


...note that the first command needs a bunch of libraries to be present and will _only_ work on Linux. See https://github.com/asciidoctor/asciidoctor-mathematical/#installation

You may also need libwebp-dev.

Oh and Ruby 2.6 won't work. Use 3.0.
