### ISSUE TITLE
Is there any requirement in the BRS specification regarding the version of UEFI implementation?

### ISSUE THREAD

**Issue by WangYin3** [riscv-non-isa/riscv-brs#92]
From the Bibliography, refence to uefi2.11, (Only find 2.10 in uefi.org).
[7] “Unified Extensible Firmware Interface Specification 2.11.” [Online]. Available: uefi.org/
specifications.
Does the BRS have a minimum requirement for the UEFI version in firmware implementation?

**Comment by andreiw** [comment]
The BRS-B requirements are to follow the EBBR spec. The BRS-I requirements are listed in https://github.com/riscv-non-isa/riscv-brs/blob/main/recipes.adoc and https://github.com/riscv-non-isa/riscv-brs/blob/main/uefi.adoc.

Note that the BRS spec doesn't duplicate UEFI spec requirements, so for BRS-I a good place to start is https://uefi.org/specs/UEFI/2.10/02_Overview.html#requirements.
