### ISSUE TITLE
SMBIOS specification points to https://github.com/riscv/riscv-smbios

### ISSUE THREAD

**Issue by xypron** [riscv-non-isa/riscv-brs#95]
The SMBIOS 3.7 specification points to https://github.com/riscv/riscv-smbios.

Can we change the README of the repository to point clearly to the new site?

We should also change the status of the old repo to sunsetted.

**Comment by andreiw** [comment]
https://github.com/riscv-non-isa/riscv-brs/issues/94

**Comment by andreiw** [comment]
Dup of 94.
